hash-format = "sha256"

[[files]]
file = "mods/adventure-platform-mod.pw.toml"
hash = "16836308db916c76ba4b25d566c0651d98ec55c1f065dd00a21660db162065cb"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "49a33ac37445e3c08eb1a958b4f81f0c9ce356a8c08ace17e5df98e18558b4b1"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "0a12f0ee21196d7b67ea4904c229b2972358bd8e2189cc481da163b848494c78"
metafile = true

[[files]]
file = "mods/better-fabric-console.pw.toml"
hash = "2ce508a2e7433dc80605342a6e3b086af3912d6d18274543c688d41decee9a67"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "ecfa58e7dc4f435480ddb8684507c797ddb73ee3a8f6d61ca5ac2f86b6b54de9"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "b6986c7bdec6840b8a344b4028b0a52be10460f2630223ca88db681b36cd5efa"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7243f5258960ac15593488a49811b27f6de0e5fce447768e4588fcff95abc757"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "274df87e6e32a96bab2135eae4aecb2f42c8df3829ce553c59e989eb022bdd12"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/convenient-mobgriefing.pw.toml"
hash = "c9127c8a26671e16730352e42f67894eafe69ee54d0640f05d45f95502b817e2"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "524e841aab4137340a1278b681268b024db28e8ad874857f0ada93db77a8d8d3"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "00de73f44c85bbe43476ba1e19098a6d0e2180bec7bdbf8199ff482e21a3a8cc"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "8eb716a02c1a27a81f2d03cec2c989553ad5a54c7380fb7982f83abb51667e79"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ffd2bde70110ba1d26bf841930556307a5bdfa3159b194e6e30ac5192be61754"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "fcd62130e02039c9af5789a548fc1c0fc00e0ba4e26ed4bc020c10e69313d25c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6f9c7fd82681111859ff63446dc8327447adeaad84e9cfb534955afb5eb6c81a"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "a6ab8a2cd68aee0f284d46ad419039a719dca1c70e41029073c66c2433961436"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "c21e5c7c86e20d26b9936224db71c94558049000dbf2481f3f1649a62b41f2a1"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "a3b275726e1953dd46c5ef4637d2ab82500c9b58be1c25325a704a9423c5deba"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d788235233cd7bb10444760f354161d730ce1c504976cfdf91bd26fcd05c9e26"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "59d6517f845164630fc10a641d2e8a3a07206e7bd9491ea58d8edddb93107264"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "af842a44a80264384c518764091621542eee6abe65fa368b13e1926c6a88c07a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "6cc155f0633b2187f5bc71357ab1d82c1d49f9592bcbd73191ec1001c98c342b"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a2f4d9dda96c16714c36b3ad813e1d720dd6d8d4bf87e5c0bbc7bf54ed62540e"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/squaremap.pw.toml"
hash = "baa82dd9ab7c57df3730ea73277c1b879888f0114305584d33e6c7b0d30ea6ca"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "9a1695184cdb4646ae5deef3ed576e7dc1235cff1ff20493aa482a2c512928b0"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "cde3e240409c0c492fae69a295ce7a2c4ae4588b5b2fbc110a556249205126ff"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dba564c761870715c46e527e182ece9d0c50ae96c8c4e3af3f2b567e2816565d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6b3f90c5a1f2c0e726010893e2dc6751a9614c30323b8b2cfd07b2f5a7728a3d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "a7ee69b752489e4dbcbe696e85bfb35670f8d6e785b63356d0645acffcb1786e"
metafile = true
