name = "Cave Game"
author = "TheMicCraft"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1482b58718ef5cc8ffb82b1f2c69b37bb5bfb12161b725faa132c2878d940e8b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
