name = "Cave Game"
author = "TheMicCraft"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebd713364242954021867e2c3eb0ec5d72f3f7cdaf8037106a79bbbf65bad2bd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
